In [4]:
# Create new venv with the following pacakges:
# pandas jupyter seaborn scikit-learn keras tensorflow

In [1]:
import pandas as pd
import jupyter 
import seaborn
import keras
import tensorflow
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor

Using TensorFlow backend.
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\Users\morga\anaconda3\envs\ml\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [2]:
# Train Data:
df = pd.read_csv('./data_2018/cd_2018.csv')
df.head()

# Target variable = 'Voter Turnout'

,CD116,Voting rate,18-44,45-64,65 and older,In Poverty,Did not finish high school,Bachelors or more,White,Black,...,Under $1,"$1 under $10,000","$10,000 under $25,000","$25,000 under $50,000","$50,000 under $75,000","$500,000 or more","$75,000 under $100,000","$100,000 under $200,000","$200,000 under $500,000",urbanization_pct
0,Indiana 01,45.644226,43.2,35.1,21.7,11.3,10.2,21.7,72.4,17.700000,...,0.928218,14.397690,20.812706,21.847006,13.755304,0.474422,10.042433,14.995875,2.746346,26.24
1,Indiana 02,43.783212,43.8,33.6,22.6,11.1,13.2,21.8,88.9,6.525141,...,1.107153,14.942119,19.789255,26.512318,15.161769,0.566934,9.400416,10.365094,2.154942,14.71
2,Indiana 03,45.467962,44.5,34.2,21.3,9.1,11.9,22.3,90.0,5.800000,...,1.082747,14.830520,19.331128,25.624064,15.014276,0.590846,9.897379,11.358946,2.270093,14.32
3,Indiana 04,43.090387,46.0,33.4,20.7,10.5,9.8,24.7,91.7,4.000000,...,1.044265,14.529791,18.573418,23.902071,14.703835,0.379997,10.271509,13.961246,2.633869,10.88
4,Indiana 05,55.305493,45.1,34.8,20.1,8.2,6.9,43.4,86.5,8.700000,...,1.096237,13.249710,15.647728,20.833773,13.389375,1.807737,9.465584,17.534521,6.975335,22.66

In [ ]:
# # Independent variables
# X = df[['18-44', '45-64', '65 and older',
#         'Did not finish high school', 'Bachelors or more',
#         'White', 'Black', 'Asian', 'Hispanic',
#         'Under $1', '$1 under $10,000', '$10,000 under $25,000',
#        '$25,000 under $50,000', '$50,000 under $75,000', '$500,000 or more',
#        '$75,000 under $100,000',
#        '$100,000 under $200,000', '$200,000 under $500,000',
#        'urbanization_pct']]

# # Dependent variable
# y = df["Voting rate"]

In [5]:
# Convert to numeric (in case of any issues) and drop missing rows
X = X.apply(pd.to_numeric, errors='coerce')
y = pd.to_numeric(y, errors='coerce')
data = pd.concat([X, y], axis=1).dropna()
X = data[['18-44', '45-64', '65 and older',
        'Did not finish high school', 'Bachelors or more',
        'White', 'Black', 'Asian', 'Hispanic',
        'Under $1', '$1 under $10,000', '$10,000 under $25,000',
       '$25,000 under $50,000', '$50,000 under $75,000', '$500,000 or more',
       '$75,000 under $100,000',
       '$100,000 under $200,000', '$200,000 under $500,000',
       'urbanization_pct']]
y = data["Voting rate"]

# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

### Mutliple Linear Regression model

In [6]:
# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Print coefficients and intercept
print("Coefficients:", dict(zip(X.columns, model.coef_)))
print("Intercept:", model.intercept_)

# Evaluate model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.3f}")
print(f"R-squared: {r2:.3f}")

Coefficients: {'18-44': -4.6637448016534, '45-64': -3.9091400465420794, '65 and older': -5.458658507625267, 'Did not finish high school': -0.9783117385597248, 'Bachelors or more': 0.05137393359437293, 'White': -0.3107902768326927, 'Black': -0.15114275706426136, 'Asian': -0.13420643722666672, 'Hispanic': 0.249904471891041, 'Under $1': 58955997.52340326, '$1 under $10,000': 58955988.16156821, '$10,000 under $25,000': 58955990.9395051, '$25,000 under $50,000': 58955988.99790059, '$50,000 under $75,000': 58955989.3766809, '$500,000 or more': 58956005.46162204, '$75,000 under $100,000': 58955992.72265772, '$100,000 under $200,000': 58955990.72664226, '$200,000 under $500,000': 58955985.55138614, 'urbanization_pct': -0.02895635925056927}
Intercept: -5895598454.088321
Mean Squared Error: 28.655
R-squared: -0.089

### Ridge Regression model

In [7]:
# Create and train the Ridge regression model
model = Ridge(alpha=1.0)  # You can tune alpha to control regularization strength
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Print coefficients and intercept
print("Coefficients:", dict(zip(X.columns, model.coef_)))
print("Intercept:", model.intercept_)

# Evaluate model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.3f}")
print(f"R-squared: {r2:.3f}")

Coefficients: {'18-44': -0.029436488601148694, '45-64': 0.9434475245839051, '65 and older': -0.7019577395667804, 'Did not finish high school': -1.0418511796470336, 'Bachelors or more': 0.045061905582065825, 'White': -0.5718063166951219, 'Black': -0.419959158270185, 'Asian': -0.12013707168917676, 'Hispanic': -0.032328165623322136, 'Under $1': 3.78811716212676, '$1 under $10,000': -2.6363748577522883, '$10,000 under $25,000': -0.38058647130430573, '$25,000 under $50,000': -2.123981440808011, '$50,000 under $75,000': -1.3362886666637626, '$500,000 or more': 4.220628776374603, '$75,000 under $100,000': 1.595430226766649, '$100,000 under $200,000': -1.5003057361860552, '$200,000 under $500,000': -1.6266389119720355, 'urbanization_pct': -0.03828509908642636}
Intercept: 216.50178072054257
Mean Squared Error: 21.686
R-squared: 0.176

### Lasso Regression

In [8]:
# Create and train the Lasso regression model
model = Lasso(alpha=0.1)  # Alpha controls regularization strength; tweak as needed
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Print coefficients and intercept
print("Coefficients:", dict(zip(X.columns, model.coef_)))
print("Intercept:", model.intercept_)

# Evaluate model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.3f}")
print(f"R-squared: {r2:.3f}")

Coefficients: {'18-44': 0.0, '45-64': 0.9176843187037451, '65 and older': -0.5595726128306524, 'Did not finish high school': -1.0395080959358542, 'Bachelors or more': -0.05968569558140615, 'White': -0.5070863678623206, 'Black': -0.3541955221726177, 'Asian': 0.0, 'Hispanic': -0.1140083941966942, 'Under $1': 4.12914454114427, '$1 under $10,000': -1.6332997019458129, '$10,000 under $25,000': 0.0, '$25,000 under $50,000': -1.1974387599273963, '$50,000 under $75,000': 0.0, '$500,000 or more': 1.680554481376286, '$75,000 under $100,000': 0.3101608611189536, '$100,000 under $200,000': -0.32853706943115885, '$200,000 under $500,000': -0.0, 'urbanization_pct': -0.04005168253799864}
Intercept: 139.41487241295164
Mean Squared Error: 19.676
R-squared: 0.252

c:\Users\morga\anaconda3\envs\ml\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.824e+00, tolerance: 2.238e-01
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

### Random Forest Regression

In [9]:
# Split into train/test sets

# Create and train the Random Forest regression model
model = RandomForestRegressor(
    n_estimators=100,      # Number of trees in the forest
    random_state=42,
    max_depth=None,        # You can set a depth limit to prevent overfitting
    min_samples_split=2
)
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Print feature importances
print("Feature importances:", dict(zip(X.columns, model.feature_importances_)))

# Evaluate model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.3f}")
print(f"R-squared: {r2:.3f}")

Feature importances: {'18-44': 0.008952220784869569, '45-64': 0.01722734905391993, '65 and older': 0.015203685646382584, 'Did not finish high school': 0.19881586220882957, 'Bachelors or more': 0.03918906566702548, 'White': 0.00676617785720664, 'Black': 0.018779371082915445, 'Asian': 0.02071806197357791, 'Hispanic': 0.008239850722781447, 'Under $1': 0.02114294933581808, '$1 under $10,000': 0.07116077626847722, '$10,000 under $25,000': 0.11256525291193127, '$25,000 under $50,000': 0.05837793935029725, '$50,000 under $75,000': 0.01375784299246654, '$500,000 or more': 0.12822970345510795, '$75,000 under $100,000': 0.04514129527483784, '$100,000 under $200,000': 0.08531713735870985, '$200,000 under $500,000': 0.10827921969288212, 'urbanization_pct': 0.022136238361963344}
Mean Squared Error: 11.550
R-squared: 0.561

In [13]:
# Data to apply model onto:
new_df = pd.read_csv('./data_2023/cd_2023.csv')
new_df.head()

,CD119,18-44,45-64,65 and older,Women,In Poverty,Did not finish high school,Bachelors or more,White,Black,Asian,Hispanic,urbanization_pct
0,Ohio 01,49.2,30.5,20.4,50.7,12.2,6.2,48.7,68.5,16.9,4.2,5.0,46.6
1,Ohio 02,41.8,33.6,24.6,50.1,14.6,9.3,21.4,92.4,1.6,0.5,1.5,10.2
2,Ohio 03,54.8,27.9,17.3,50.5,16.6,8.2,46.0,54.1,28.0,5.8,7.3,86.0
3,Ohio 04,43.3,33.0,23.7,49.2,10.8,7.2,28.9,85.7,3.9,3.4,2.8,13.8
4,Ohio 05,42.6,32.0,25.3,50.2,10.9,6.4,26.3,85.8,3.4,1.0,7.6,13.4

In [14]:
new_X = new_df[X.columns]  # ensure same feature order

new_predictions = model.predict(new_X)

new_df["Voter Turnout"] = new_predictions

predict_df = new_df[["CD119", "Voter Turnout"]].copy()

predict_df["Voter Turnout"] = predict_df["Voter Turnout"].round(2)

print(predict_df.head())

     CD119  Voter Turnout
0  Ohio 01          53.95
1  Ohio 02          48.65
2  Ohio 03          54.24
3  Ohio 04          53.66
4  Ohio 05          50.26

In [15]:
# Export
# predict_df.to_csv('./data_2023/predict_turnout_ohio_2026.csv', index=False)